#!/bin/sh /etc/rc.common
# Copyright (C) 2014 Drasko DRASKOVIC

START=01

start() {
    echo "Blinking the LEDs"
    /weio/scripts/ledBlink.py 0.5 &
}


stop() {
	if [ -n "$(ps | grep  "[l]edBlink.py")" ]; then
        echo "Stopping ledBlink.py..."
        killall ledBlink.py
       
        # Light up the correct LED 
        MODE=`iwconfig wlan0 | grep Mode | awk '{print $1}' | sed 's/Mode://'`
        if [ $MODE == Managed ]; then
       	    echo 1 > /sys/class/leds/weio:green:sta/brightness
        else
       	    echo 1 > /sys/class/leds/weio:green:ap/brightness
       fi
	fi
}
