#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99
start() {
    echo "Launching WeIO application"
    cd /
    ./run_weio.sh
}

stop() {
    echo "Stopping WeIO application"

    if [ `ps | grep  "run_weio.sh" | wc -l` != "1" ]; then
        RUN_WEIO_PID=`ps | grep  "run_weio.sh" | head -1 | awk '{print $1}'`
        kill -9 $RUN_WEIO_PID
    fi


    if [ `ps | grep  "python server.py" | wc -l"` != "1" ]; then
        WEIO_PID=`ps | grep  "python server.py" | head -1 | awk '{print $1}'`
        kill -9 $WEIO_PID
    fi
}
