#!/bin/sh /etc/rc.common

START=11

start() {
	echo "*** GPIO22=0" > /dev/kmsg
	echo 22 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio22/direction
	echo 0 > /sys/class/gpio/gpio22/value
	echo 22 > /sys/class/gpio/unexport
}

stop() {
	return
}

restart() {
	return
}
