#!/bin/sh /etc/rc.common

START=09

start() {
	echo "*** GPIO17=1" > /dev/kmsg
	echo 17 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio17/direction
	echo 1 > /sys/class/gpio/gpio17/value
	echo 17 > /sys/class/gpio/unexport
}

stop() {
	return
}

restart() {
	return
}
