#!/bin/sh /etc/rc.common

START=11

start() {
	echo "*** GPIO17=0" > /dev/kmsg
	echo 17 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio17/direction
	echo 0 > /sys/class/gpio/gpio17/value
	echo 17 > /sys/class/gpio/unexport
}

stop() {
	return
}

restart() {
	return
}
