#!/bin/sh /etc/rc.common

START=09

start() {
	echo "*** GPIO22=1" > /dev/kmsg
	echo 22 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio22/direction
	echo 1 > /sys/class/gpio/gpio22/value
	echo 22 > /sys/class/gpio/unexport
}

stop() {
	return
}

restart() {
	return
}
