#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

start() {
    echo "Launching WeIO application"
    cd /
    ./weio_run_forever.sh
}

stop() {
    echo "Stopping WeIO application"
    
    # Trick for avoiding grep to show in ps command: 
    # http://stackoverflow.com/questions/9375711/more-elegant-ps-aux-grep-v-grep
    # http://www.perlmonks.org/bare/?node_id=203760
    if [ -n "$(ps | grep "[w]eio_run_forever.sh")" ]; then
    	echo "Stopping weio_run_forever.sh..."
    	killall weio_run_forever.sh
    fi
    
    if [ -n "$(ps | grep  "[w]eioServer.py")" ]; then
    	echo "Stopping python server.py..."
    	killall weioServer.py
    fi
    
    if [ -n "$(ps | grep  "[w]eioRunner.py")" ]; then
        echo "Stopping user program weioRunner.py..."
        killall weioRunner.py
    fi
    
}
