#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

start() {
    echo "Launching WeIO application"
    cd /
    cp /weio/scripts/run_weio.sh /weio_run_forever.sh
    /weio_run_forever.sh&
}

stop() {
    echo "Stopping WeIO application"

    # Trick for avoiding grep to show in ps command:
    # http://stackoverflow.com/questions/9375711/more-elegant-ps-aux-grep-v-grep
    # http://www.perlmonks.org/bare/?node_id=203760
    if [ -n "$(ps | grep "[w]eio_run_forever.sh")" ]; then
        echo "Stopping weio_run_forever.sh..."
        killall weio_run_forever.sh
    fi

    if [ -n "$(ps | grep  "[w]eioServer.py")" ]; then
        echo "Stopping python server.py..."
        SPID=`ps | grep  "[w]eioServer.py" | awk '{print $1}'`
        kill -9 $SPID
    fi

    if [ -n "$(ps | grep  "[w]eioRunner.py")" ]; then
        echo "Stopping user program weioRunner.py..."
        RPID=`ps | grep  "[w]eioRunner.py" | awk '{print $1}'`
        kill -9 $RPID
    fi
}

restart() {
    stop
    start
}

