from weioLib import weio
import random


# Click on button in browser
def buttonHandler(dataIn) :
    # Button state from browser
    print "FROM BROWSER: ", dataIn
    
    # How many clients have been connected
    print "N of clients " + str(len(weio.shared.connectedClients))
    
    # Iterate thru array of connected clients
    for websocket in weio.shared.connectedClients:
        
        # Get client information. Refer to navigator javascript object for keys
        # Few keys were added to enrich base navigator object
        # "uuid" is unique number generated by client and sent on each new connection
        # "ip" is client ip address detected by server
        print "******************************************"
        print "CLIENT " + websocket.info["uuid"]
        print "IP " + websocket.info["ip"]
        print "PLATFORM " + websocket.info["platform"]
        print "APP NAME " + websocket.info["appCodeName"]
        print "******************************************"
        # Generate some random integer and send to all clients, change is immediate and
        # in all browsers at once
        websocket.send("userMsg", random.randint(0,10))
        
        
# Attaches interrupt from Web client to "message" string
weio.attach.event('message', buttonHandler)