#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=15
start() {
    echo "Preparing STA mode"
    # Copy STA files
    cp /etc/config/network.sta /etc/config/network
    cp /etc/config/wireless.sta /etc/config/wireless

    cp /etc/config/dhcp.sta /etc/config/dhcp
    cp /etc/config/firewall.sta /etc/config/firewall
}
